AllCops:
  TargetRubyVersion: 3.0
  NewCops: "enable"
  Exclude:
    - "bin/**/*"
    - "Gemfile"
    - "Rakefile"
  SuggestExtensions: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/Documentation:
  Enabled: false

Style/LambdaCall:
  EnforcedStyle: braces

Style/StringLiterals:
  EnforcedStyle: double_quotes
